### ISSUE TITLE
MCDW and MCDA Usage

### ISSUE THREAD

**Issue by chronosacaria** [FettLol/fettlol-modpack-beta#1]
Hi y'all!

I wanted to write concerning the use of MCDW and MCDA in your pack. We have no issue with you including our mods in your pack, however, you are not allowed to rehost them on your website. We ask that you either redirect the link to the respective CurseForge pages or remove them from your pack. As is stated in the FAQ on every mod's page: you are more than welcome to use our mods in a modpack, however, we ask that you provide a linkback.

We want to see our mods used in as many places as possible, but at the same time, we ask that modpack developers respect where we have chosen to host our files and not rehost them. As you have links out to Modrinth, this does not seem like an unreasonable request.

Thank you, so much!

Sincerely,
Chronos

**Comment by BrekiTomasson** [comment]
Sorry for the late answer, I haven't been following the issues in this repo. 

While I am technically in the green (because I am rehosting your old MIT release), I absolutely understand your concerns and would be happy to oblige. However, CurseForge does not offer direct downloads, which is a requirement for the modpack because of the modpack loader that I am using.

If you were to publish your mods on Modrinth or Minepkg, I could load your mod from there, but while you insist on distributing your mod only through CurseForge, this is not possible and I am more likely to remove your all of your mods from the modpack instead.

**Comment by chronosacaria** [comment]
Thank you for obliging. 

As Modrinth doesn't have monetisation options, at this time, we won't be uploading to there yet. Once that happens, though, we will be able to consider it. 

At this time, it would probably be better to just remove the Timefall mods from your pack until such a time as we're able to consider putting them on Modrinth

**Comment by BrekiTomasson** [comment]
Don't worry about it; I'm not going to support or promote any mod where the developers are so obvious about looking to monetize it. I'll have it out of the modpack and removed from the modpack's official server by the end of the week.
